name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0           # لازم لـ nx affected

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps

      # لو عندك E2E بـ Cypress وعايز تشغلها في CI
      # - run: npx cypress install

      # شغّل المشاريع "المتأثرة فقط" (أسرع كثيراً)
      - run: npx nx affected -t lint test build --parallel=3 --base=origin/main --head=HEAD
      # لو عايز تشغّل E2E كمان:
      # - run: npx nx affected -t e2e --parallel=1
